<?php
/**
 * SureFormsCreateForm.
 * php version 5.6
 *
 * @category SureFormsCreateForm
 * @package  SureTriggers
 * @author   BSF <username@example.com>
 * @license  https://www.gnu.org/licenses/gpl-3.0.html GPLv3
 * @link     https://www.brainstormforce.com/
 * @since    1.0.0
 */

namespace SureTriggers\Integrations\SureForms\Actions;

use SureTriggers\Integrations\AutomateAction;
use SureTriggers\Traits\SingletonLoader;

/**
 * SureFormsCreateForm
 *
 * Creates a SureForms form from a title and a JSON list of fields by reusing
 * SureForms' own `sureforms/create-form` ability, so the block markup, block IDs
 * and default form meta are generated by SureForms itself.
 *
 * @category SureFormsCreateForm
 * @package  SureTriggers
 * @author   BSF <username@example.com>
 * @license  https://www.gnu.org/licenses/gpl-3.0.html GPLv3
 * @link     https://www.brainstormforce.com/
 * @since    1.0.0
 */
class SureFormsCreateForm extends AutomateAction {

	/**
	 * Integration type.
	 *
	 * @var string
	 */
	public $integration = 'SureForms';

	/**
	 * Action name.
	 *
	 * @var string
	 */
	public $action = 'sureforms_create_form';

	/**
	 * Upper bounds for the fields input, to avoid huge payloads.
	 *
	 * @var int
	 */
	const MAX_FIELDS_JSON_LENGTH = 200000;

	/**
	 * Maximum number of fields in one form.
	 *
	 * @var int
	 */
	const MAX_FIELDS = 100;

	use SingletonLoader;

	/**
	 * Register a action.
	 *
	 * @param array $actions actions.
	 * @return array
	 */
	public function register( $actions ) {
		$actions[ $this->integration ][ $this->action ] = [
			'label'    => __( 'Create Form', 'suretriggers' ),
			'action'   => $this->action,
			'function' => [ $this, 'action_listener' ],
		];
		return $actions;
	}

	/**
	 * Action listener.
	 *
	 * @param int   $user_id user_id.
	 * @param int   $automation_id automation_id.
	 * @param array $fields fields.
	 * @param array $selected_options selectedOptions.
	 * @psalm-suppress UndefinedMethod
	 *
	 * @return array
	 */
	public function _action_listener( $user_id, $automation_id, $fields, $selected_options ) {
		if ( ! class_exists( '\SRFM\Plugin_Loader' ) ) {
			return $this->error_response( 'SureForms plugin is not active.' );
		}

		// The create-form ability shipped in SureForms 2.5.2.
		if ( ! class_exists( '\SRFM\Inc\Abilities\Forms\Create_Form' ) ) {
			return $this->error_response( 'Please update SureForms to version 2.5.2 or later to use this action.' );
		}

		$form_title = isset( $selected_options['form_title'] ) && is_string( $selected_options['form_title'] ) ? sanitize_text_field( $selected_options['form_title'] ) : '';
		if ( '' === $form_title ) {
			return $this->error_response( 'Form title is required.' );
		}

		$ability = new \SRFM\Inc\Abilities\Forms\Create_Form();

		if ( ! is_callable( [ $ability, 'execute_wrapper' ] ) ) {
			return $this->error_response( 'Please update SureForms to version 2.5.2 or later to use this action.' );
		}

		$form_fields = $this->parse_form_fields( isset( $selected_options['form_fields'] ) ? $selected_options['form_fields'] : '' );
		if ( empty( $form_fields ) ) {
			return $this->error_response( 'Form fields must be a valid JSON array with at least one field, e.g. [{"label":"Name","fieldType":"input"}].' );
		}

		if ( count( $form_fields ) > self::MAX_FIELDS ) {
			return $this->error_response( 'A form can have at most ' . self::MAX_FIELDS . ' fields.' );
		}

		$field_error = $this->validate_form_fields( $form_fields, $this->get_allowed_field_types( $ability ) );
		if ( '' !== $field_error ) {
			return $this->error_response( $field_error );
		}

		$allowed_statuses = [ 'publish', 'draft', 'private' ];
		$form_status      = isset( $selected_options['form_status'] ) && is_string( $selected_options['form_status'] ) ? sanitize_text_field( $selected_options['form_status'] ) : 'draft';
		if ( ! in_array( $form_status, $allowed_statuses, true ) ) {
			$form_status = 'draft';
		}

		// execute_wrapper() also fires SureForms' before/after ability hooks.
		$result = $ability->execute_wrapper(
			[
				'formTitle'  => $form_title,
				'formFields' => $form_fields,
				'formStatus' => $form_status,
			]
		);

		if ( is_wp_error( $result ) ) {
			return $this->error_response( $result->get_error_message() );
		}

		return $result;
	}

	/**
	 * Turn the "form fields" input into a clean list of field definitions.
	 *
	 * Accepts an array or a JSON string. Markdown code fences and surrounding prose
	 * (common in LLM output) are tolerated, as is a `{"formFields": [...]}` wrapper.
	 *
	 * @param mixed $raw Raw field input.
	 * @return array Decoded list of fields (not yet validated).
	 */
	private function parse_form_fields( $raw ) {
		$decoded = $raw;

		if ( is_string( $raw ) ) {
			if ( strlen( $raw ) > self::MAX_FIELDS_JSON_LENGTH ) {
				return [];
			}

			$raw = trim( $raw );

			// Strip markdown code fences without regex (LLMs often wrap JSON in them).
			if ( 0 === strpos( $raw, '```' ) ) {
				$newline = strpos( $raw, "\n" );
				$raw     = false !== $newline ? substr( $raw, $newline + 1 ) : '';
			}
			if ( '```' === substr( $raw, -3 ) ) {
				$raw = rtrim( substr( $raw, 0, -3 ) );
			}

			$decoded = json_decode( $raw, true );

			if ( ! is_array( $decoded ) ) {
				$start = strpos( $raw, '[' );
				$end   = strrpos( $raw, ']' );
				if ( false !== $start && false !== $end && $end > $start ) {
					$decoded = json_decode( substr( $raw, $start, $end - $start + 1 ), true );
				}
			}
		}

		if ( ! is_array( $decoded ) ) {
			return [];
		}

		if ( isset( $decoded['formFields'] ) && is_array( $decoded['formFields'] ) ) {
			$decoded = $decoded['formFields'];
		}

		return array_values( $decoded );
	}

	/**
	 * Field types accepted by the SureForms create-form ability.
	 *
	 * Read from the ability's own input schema so Pro/third-party types added via
	 * SureForms filters are picked up without hard-coding a list here.
	 *
	 * @param object $ability Create_Form ability instance.
	 * @return array
	 */
	private function get_allowed_field_types( $ability ) {
		if ( ! is_callable( [ $ability, 'get_input_schema' ] ) ) {
			return [];
		}

		$schema = $ability->get_input_schema();
		$types  = is_array( $schema ) && isset( $schema['properties']['formFields']['items']['properties']['fieldType']['enum'] )
			? $schema['properties']['formFields']['items']['properties']['fieldType']['enum']
			: [];

		return is_array( $types ) ? $types : [];
	}

	/**
	 * Validate the field list so problems are reported instead of being silently
	 * dropped or coerced by SureForms (an unknown fieldType becomes a text input).
	 *
	 * @param array $form_fields Parsed fields.
	 * @param array $allowed_types Supported fieldType values. Empty skips the type check.
	 * @return string Error message, or an empty string when valid.
	 */
	private function validate_form_fields( $form_fields, $allowed_types ) {
		foreach ( $form_fields as $index => $field ) {
			$position = (int) $index + 1;

			if ( ! is_array( $field ) || empty( $field['label'] ) || ! is_string( $field['label'] ) || empty( $field['fieldType'] ) || ! is_string( $field['fieldType'] ) ) {
				return 'Field #' . $position . ' must have a "label" and a "fieldType".';
			}

			if ( ! empty( $allowed_types ) && ! in_array( $field['fieldType'], $allowed_types, true ) ) {
				return 'Field #' . $position . ' has an unsupported fieldType "' . sanitize_text_field( $field['fieldType'] ) . '". Supported types: ' . implode( ', ', $allowed_types ) . '.';
			}
		}

		return '';
	}

	/**
	 * Build the standard error response returned by actions.
	 *
	 * @param string $message Error message.
	 * @return array
	 */
	private function error_response( $message ) {
		return [
			'status'  => 'error',
			'message' => $message,
		];
	}
}

SureFormsCreateForm::get_instance();
